package dev.terrarealis.fabric.worldgen;

import com.mojang.serialization.MapCodec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import dev.terrarealis.kernel.TerraKernel;
import dev.terrarealis.kernel.biome.BiomeKind;
import net.minecraft.core.Holder;
import net.minecraft.core.HolderGetter;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.RegistryOps;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.biome.BiomeSource;
import net.minecraft.world.level.biome.Biomes;
import net.minecraft.world.level.biome.Climate;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

/**
 * The biome source.
 *
 * <p>Biomes are <i>derived</i>, never stored: the classifier in the kernel decides the biome from the
 * same column the terrain was built from, so a biome can never disagree with the ground it labels. A
 * desert biome sits on desert soil over desert rock; a river biome sits in a channel that the
 * hydrology actually carved.
 *
 * <p>The mod registers no biomes of its own. Each of the kernel's {@link BiomeKind}s maps onto a vanilla
 * biome id, so every vanilla feature, structure, mob spawn and advancement that keys on a biome keeps
 * working, and a world generated by this mod remains loadable with the mod removed.
 */
public class RealisBiomeSource extends BiomeSource {

    public static final MapCodec<RealisBiomeSource> CODEC = RecordCodecBuilder.mapCodec(i -> i
            .group(RegistryOps.retrieveGetter(Registries.BIOME))
            .apply(i, RealisBiomeSource::new));

    private final List<Holder<Biome>> biomes;
    private final Holder<Biome>[] byKind;
    private final Holder<Biome> fallback;

    @SuppressWarnings("unchecked")
    public RealisBiomeSource(HolderGetter<Biome> getter) {
        this.fallback = getter.getOrThrow(Biomes.PLAINS);
        this.biomes = new ArrayList<>();
        this.byKind = new Holder[BiomeKind.values().length];
        for (BiomeKind kind : BiomeKind.values()) {
            ResourceKey<Biome> key = ResourceKey.create(Registries.BIOME,
                    Identifier.parse(kind.qualifiedId()));
            Holder<Biome> h = getter.get(key).orElse(this.fallback);
            this.byKind[kind.ordinal()] = h;
            if (!this.biomes.contains(h)) {
                this.biomes.add(h);
            }
        }
    }

    @Override
    protected MapCodec<? extends BiomeSource> codec() {
        return CODEC;
    }

    @Override
    protected Stream<Holder<Biome>> collectPossibleBiomes() {
        return this.biomes.stream();
    }

    @Override
    public Holder<Biome> getNoiseBiome(int biomeX, int biomeY, int biomeZ, Climate.Sampler sampler) {
        TerraKernel kernel = KernelHolder.kernel();
        dev.terrarealis.kernel.Column scratch = SCRATCH.get();
        int x = biomeX << 2;
        int z = biomeZ << 2;
        int y = biomeY << 2;
        BiomeKind kind = kernel.biomeAt(x, y, z, scratch);
        if (kind == null) {
            return this.fallback;
        }
        if (y < scratch.surfaceY) {
            BiomeKind sub = BiomeKindSubterranean.of(kernel, scratch, y);
            if (sub != null) {
                return this.byKind[sub.ordinal()];
            }
        }
        return this.byKind[kind.ordinal()];
    }

    private static final ThreadLocal<dev.terrarealis.kernel.Column> SCRATCH =
            ThreadLocal.withInitial(dev.terrarealis.kernel.Column::new);

    /** Keeps the subterranean classification out of the hot method body. */
    private static final class BiomeKindSubterranean {
        static BiomeKind of(TerraKernel kernel, dev.terrarealis.kernel.Column col, int y) {
            dev.terrarealis.kernel.biome.BiomeClassifier.Env e = new dev.terrarealis.kernel.biome.BiomeClassifier.Env();
            e.latitude = col.latitude;
            e.surfaceY = col.surfaceY;
            e.tempC = col.tempC;
            e.precipMm = col.precipMm;
            e.aridity = col.aridity;
            e.elevationM = col.elevationM;
            e.slopeDeg = col.slopeDeg;
            e.karst = col.karst;
            e.rock = col.rock;
            e.soil = col.soil;
            e.saturation = col.saturation;
            e.params = kernel.params();
            return dev.terrarealis.kernel.biome.BiomeClassifier.subterranean(e, y);
        }
    }
}
